from genetics_api import patches
from genetics_api.resources.phylotree import *


pairs = [
    ('Spodoptera frugiperda', '''HVDSGKSTTTGHLIYKCGGIDKRTIEKFEKEAQEMGKGSFKY
        AWVLDKLKAERERGITID
        IALWKFETAKYYVTIIDAPGHRDFIKNMITGTSQADCAVLIVAAGTGEFEAGISKNGQTR
        EHALLAFTLGVKQLIVGVNKMDSTEPPYSESRFEEIKKEVSSYIKKIGYNPAAVAFVPIS
        GWHGDNMLEASTKMPWFKGWNVERKEGKAEGKCLIEALDAILPPARPTDKPLRLPLQDVY
        KIGGIGTVPVGRVETGILKPGTIVVFAPANITTEVKSVEMHHEALQEAVPGDNVGFNVKN
        VSVKELRRGYVAGDSKNNPPKGAADFTAQVIVLNHPGQISNGYTPVLDCHTAHIACKFAE
        IKEKVDRRTGKSTEDNPKSIKSGDAAIVNLVPSKPLCVESFQEFPPLGRFAVR
    '''),
    ('Helicoverpa zea', '''HVDSGKSTTTGHLIYKCGGIDKRTIEKFEKEAQEMGKGSFKYAWVLDK
        LKAERERGITID
        IALWKFETAKYYVTIIDAPGHRDFIKNMITGTSQADCAVLIVAAGTGEFEAGISKNGQTR
        EHALLAFTLGVKQLIVGVNKMDSTEPPYSESRFEEIKKEVSSYIKKIGYNPAAVAFVPIS
        GWHGDNMLEASTKMPWFKGWNVERKEGKAEGKCLIEALDAILPPARPTDKALRLPLQDVY
        KIGGIGTVPVGRVETGILKPGTIVVFAPANITTEVKSVEMHHEALQEAVPGDNVGFNVKN
        VSVKELRRGYVAGDSKNNPPKGAADFTAQVIVLNHPGQISNGYTPVLDCHTAHIACKFAE
        IKEKVDRRTGKSTEDNPKSIKSGDAAIVNLVPSKPLCVESFQEFPPLGRFAVR
    ''')
]


print(get_tree_bytes(pairs))
